### ISSUE TITLE
join in Doocs

### ISSUE THREAD

**Issue by Radom7** [doocs/intro#4]
join in Doocs!

**Comment by yanglbme** [comment]
@Radom7 Welcome
> You've invited Radom7 to Doocs! They'll be receiving an email shortly. They can also visit https://github.com/doocs to accept the invitation.

**Comment by bruceFend** [comment]
apply to join in @yanglbme

**Comment by yanglbme** [comment]
@bruceFend welcome

> You've invited bruceFend to Doocs! They'll be receiving an email shortly. They can also visit https://github.com/doocs to accept the invitation.

**Comment by Xin1452** [comment]
apply to join in @yanglbme

**Comment by yanglbme** [comment]
@Xin1452 欢迎你加入，我已经给你发邀请啦。

**Comment by purain** [comment]
apply to join in @yanglbme

**Comment by yanglbme** [comment]
@purain 
> You've invited purain to Doocs! They'll be receiving an email shortly. They can also visit https://github.com/doocs to accept the invitation.
