### ISSUE TITLE
微信交流群，欢迎 GitHub 爱好者们加入

### ISSUE THREAD

**Issue by yanglbme** [doocs/intro#6]
GitHub 爱好者可以加入。

- 虽然微信群放这里，很难被发现。但我也相信，能发现这个 issue 的人，一定对 GitHub 有着一定的热情，欢迎你们加入进来，与其它朋友们一起交流。
- 群内禁止一切垃圾广告信息，仅交流 GitHub、开发知识相关。
- 进群请看公告。

![image](https://user-images.githubusercontent.com/21008209/54401127-4a623400-4701-11e9-9bd1-a2f9044317f3.png)

**Comment by yanglbme** [comment]
# 并不是所有的 GitHub 写在简历上都加分
> 原文出处：[果哥简历](https://mp.weixin.qq.com/s?__biz=MzIwMDM5NDQ0Nw==&mid=2470822543&idx=1&sn=cb57a1a9a2278aa7eda6bf6ac41a4641&chksm=804cb12fb73b383945a93b14da4dc1e8469b7cfe19f3781fe10544ffdf88cb9d3ee900eada9d&mpshare=1&scene=1&srcid=0314ih38sQ9ZWkWCRq1JyiMD&key=f7a27f56e4027020925c10b43948c5578dcc485558e5726a4275d74baf1d1ee5c58c8d99afd3dc6d1441c5211b1bdf59897b82a4f19e0b8144406e6027671eb7b42e47c3086ebab9c70a0fbb5baf38da&ascene=1&uin=MjUzNTM1MDIyNQ%3D%3D&devicetype=Windows+10&version=62060728&lang=zh_CN&pass_ticket=Emqz9AJR534NEZvdQKxBDlGHDgb%2B2z%2Ff1PX2jBIIAap0QC2I6Jdzqk8p3e%2FQNbP2)，我在这里稍做了些调整。

## 为什么 GitHub 可以加分
很多招聘描述上面都会备注 GitHub 加分项，那么为什么它是加分项呢？停，如果看到这里你还不知道 GitHub 是什么，可以看一下 Phodal 的[手记](https://github.com/phodal/github)。

### 社区光环
众所众知，GitHub 是开发者的“同性交友社区”。[Google](https://github.com/google), [FaceBook](https://github.com/facebook), [Alibaba](https://github.com/alibaba) 都在通过它来贡献自己的开源项目。如果你留心关注，公司越大 GitHub 的贡献度越高，那么如果你想进入大的互联网公司，是不是也提前融入一下这个氛围？同时对于求知的小伙伴儿想阅读源码没有什么比它来的更直接了。

### 代码工具
基本上 90% 以上的公司都使用 Git 系工具 (GitLab, Gitee, GitHub ) 做项目源码管理，你的提交记录是最好的证明你的 Git 基本功，要比在简历上写熟练使用 Git 更有说服力。那么一个题外话，如果你也热衷于维护 StackOverflow 账号，写上也是一种加分。

### 编程习惯
*Talk is cheap, show me the code.*  这句话想必大家都知道吧。 GitHub 上面的代码能够最直观的看到你的编程风格和能力，面试官在背调的时候可以通过你的代码结构，更深入的了解你，好的编程规范会在面试前就留下一个很好的印象。大多数面试官希望看到这种能够真正展示你能力的东西，而不是只是在简历上写会什么什么。作为面试官，大多数是来看人们的编码习惯，不管人家写这个东西是为了什么的。

### 技术热情
如果你钟情于购物你第一想到的可能是小红书，如果你钟情于阅读第一想到的可能“蜗牛读书”(笔者在用很不错的读书 App)，如果你钟情于看新闻第一想到的可能是腾讯新闻。然而如果你钟情于技术第一想到的可能是 GitHub。只有一个钟情技术的人，才会想像朋友圈一样每天关注 GitHub、维护 GitHub。所以你“绿油油”的 GitHub 是你的技术热情的最好体现。你看到下图会动心吗？

![1](https://user-images.githubusercontent.com/21008209/54424750-925b7800-474e-11e9-91fb-ddf73105b6e3.png)

曾经一个技术很不错的小伙伴终面的时候挂了，面试系统中的备注是：“看不到他对技术的热情”。所以这也会作为面试的一个考量。

### 英文水平
常用 GitHub 的朋友可能不觉得，但是对于普遍互联网公司的朋友们，英语都是致命的伤痛。虽然 GitHub 简单的操作英文并不是那么难，但是想把它玩透，还是需要一些功底的。如果你没用那么好的英语底子也能玩透，无论是你的英文熟悉能力还是适应能力都是可以肯定的。对了，还有你的 repository 的命名。这不比写上四六级证书来的实际？

### 涉猎领域
你的圈子决定了你的水平，一样的道理。你的 GitHub 的 follow, star, followers, repository, pull request 还有你获得的 star 数，都是在展示你的涉猎，关注和掌握程度。你的一个 ElasticSearch 的 PullRequest 被 Merge 远比你的一句“精通 ElasticSearch”要更有说服力。

### 情投意合
村子里面的阿姨每天就聊聊哪个市场的白菜最新鲜，那么你如果有好的 star 或者好的开源贡献，这会让面试官在面试你的时候有东西可聊。如果他喜欢上你的 repository 而侃侃而谈，那么结果会怎么样呢？

### 开源贡献
开源贡献不一定非要有一个几 K 的 star，而是你对于开源的那份热忱。可以是好的资源整理，也可以是自己找到了痛点做的一个很小的工具，或者是使用别人的工具提的 pull request。都是你对开源的那一份热忱。你从开源一直索取，适当的给予更能体现一个人的心智。

### 与众不同
虽然上面说了 GitHub 的好处多多，但是国内的技术圈子能持续坚持 GitHub 的人还是太少了，所以变成了如果你有一个不错的 GitHub 写到简历上面也算是一道风景线了。

笔者每天阅读近百份简历，能有不错 GitHub 的人寥寥无几。

## 为什么没有亮点反而减分
### 僵尸粉
一进来 GitHub 主页只有几个空项目，名字很奇怪也没有 star，点击进去杂乱的项目目录，提交记录和中文提交备注。那么这样的 GitHub 不仅没有提分的亮点，而且还会大大折扣面试官的印象。

### 零参与
**别人都是“绿油油”的草地，你这是撒哈拉沙漠**，那么一点也体现不出来你对技术的热情，持续的学习。

### 短而小
如果都是 HelloWorld 一样的 demo 是完全没有说服力的。

### 乱投机
自己没有贡献代码，只是因为提交了 issue 可以把别人的 repository 固定到自己的 GitHub Profile 首页。这样不但不能加分反而减分。这样就好比随意粘贴来别人辛苦写的公众号文章作为自己的原创一样。

### 乱命名
这几天在收到的简历里面发现了好多 GitHub 命名方式千奇百怪，比如 X00000000X 、LZ00000000、ZUOYE20170909。这可是你的用户名，一来方便别人访问和记住，二来你这个命名都这么不规范，何况是项目，类，方法呢？

### 不专业
切记，想提高自己也好，想开源小东西也好，切记不能再上班时间整理自己的代码，如果面试官一看你的所有提交记录都是周一到周五的上班时间，那么你想他还会聘请你吗？我的意思不是说让你工作日写完，周末去提交，而是 GitHub 是体现你业余时间的一个贡献度。

## 怎么样让自己的 GitHub 加分
### 习惯
良好的使用习惯，就像是每天来看朋友圈一样，不一定每天都有东西要提交，但是一定要一直有一个 repository 在维护，持续的提交代码。同时也要注意自己的 repository 的命名，提交代码保证一次的功能完备，提交备注要清晰明了。

### 持久
可以试着翻译外文，写博客，或者是自己做一个有意思的小程序，每天坚持编写代码，提交代码。但是一定要注意每次提交的功能完整性和备注。

### 贡献
很多方式可以贡献开源社区，有一个话说的非常好，我们做程序不是总知道提出问题，而是提出问题并有解决方案。那么你可以提交 issue 给你觉得有问题的软件，如果没有理睬自己修改，然后提交 pull request。或者自己做一些脚手架，多少有一些实际的功能，当然我们不希望重复制造轮子，你在创造的时候还是提前去检索一番。不过这个时候你需要了解一下开源协议，合理的使用别人的源码和开源自己的源码。

### 文档
开发人员处理编码，更重要的是能写出完备的文档，所以如果你开源了项目，一定要详细的写出说明问题。这不仅体现出你的编写文档能力，还能体现你的逻辑能力。

### 关注
原来你可能使用 Google 来解决问题，告诉你一个新方法，遇到问题可以按照自己提炼的关键字来 GitHub 搜索，没准能找到意想不到的结果。而后呢 Fork 或者 Star 这个你得到的结果，慢慢的你就真正的把 GitHub 用起来了。

### 英文
试着不要给 repository 起拼音名字，试着用英文写 README，试着每一个提交都是英文，并每次都要斟酌。

### 博客
一个 GitHub Pages 的博客对于有技术热忱的极客来说，比每天在 CSDN 写博客要专业很多。可以没有自己的域名，自带的域名也可以带飞。不过这里需要补充一点，不是一拥有了一个博客就加分，而是你是不是在持续的维护这个博客。

### 简历
写一份 Markdown 的简历也是一个不错的选择，极客一般都喜欢使用 Markdown 写文章，写文档，有的时候就连周报也用。那么你写一个 Markdown 的简历也是一个亮点诶。比如按照如下格式写一个简历放在自己的 GitHub 。跳槽的必要条件是有一份好的简历。

**Comment by Angel-guo** [comment]
nice

**Comment by Angel-guo** [comment]
二维码不过二维码过期了

**Comment by koreQAQ** [comment]
大佬，二维码过期啦~

**Comment by yanglbme** [comment]
@koreQAQ @Angel-guo 稍后更新群二维码至 intro 项目首页。

**Comment by yanglbme** [comment]
@koreQAQ @Angel-guo  二维码已更新至 https://github.com/doocs/intro#documentation
